[package]
name = "rust_minify"
version = "0.1.0"
authors = ["Pavel Kvasnikov <camokpyt@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.3.16"
rocket_codegen = "0.3.16"
rocket_contrib = "*"
minifier = "^0.0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
